name: Deploy Counselling App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend to AWS Lightsail
    runs-on: ubuntu-latest

    env:
      LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
      SSH_KEY: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
      USERNAME: ubuntu
      PROJECT_DIR: oman-dashboard
      ENV_FILE_PATH: /home/ubuntu/oman/.env/.env.development
      APP_NAME: oman-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            # Verify Node.js and npm installation
            node -v || { echo "Node.js not found"; exit 1; }
            npm -v || { echo "npm not found"; exit 1; }

            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Clone the repository or pull the latest changes
            if [ -d "${{ env.PROJECT_DIR }}" ]; then
              cd ${{ env.PROJECT_DIR }}
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }} ${{ env.PROJECT_DIR }}
              cd ${{ env.PROJECT_DIR }}
            fi

            # Install dependencies
            cd omanDashboard-backend
            npm install

            # Copy environment file
            if [ -f "${{ env.ENV_FILE_PATH }}" ]; then
              cp ${{ env.ENV_FILE_PATH }} .env
            else
              echo ".env file missing at ${{ env.ENV_FILE_PATH }}"
              exit 1
            fi

            # Restart the application with PM2
            pm2 delete ${{ env.APP_NAME }} || true
            pm2 start npm --name ${{ env.APP_NAME }} -- run start
            pm2 save

  deploy-frontend:
    name: Deploy Frontend to AWS Lightsail
    runs-on: ubuntu-latest
    needs: deploy-backend

    env:
      LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
      SSH_KEY: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
      USERNAME: ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: |
          cd Oman-frontend
          npm ci
          npm run build

      - name: Rename dist to oman-frontend
        run: mv Oman-frontend/dist ./oman-frontend

      - name: Copy Files to Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          source: ./oman-frontend/
          target: ~/deploy-temp/

      - name: Deploy on Lightsail
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            # Remove old deployment
            sudo rm -rf /var/www/html/oman-frontend

            # Move new files to the deployment directory
            sudo mv ~/deploy-temp/* /var/www/html/oman-frontend

            # Remove temporary deployment folder
            sudo rm -rf ~/deploy-temp

            # Restart NGINX to apply changes
            sudo systemctl restart nginx
